# References:
# 1. https://github.com/docker/awesome-compose/tree/master/frontnet-postgres

###
# Run: docker compose up --build

##### NOTE ###########################################
#### THIS DOCKER COMPOSE IS FOR RELEASE DEVELOPMENT ####
######################################################
services:

  ktv_reverse_proxy_service:
    image: ${REGISTRY}/ktv_reverse_proxy_img:${VERSION}
    ports:
      # HOST_PORT:CONTAINER_PORT
      - "6868:8888"      # HTTP plain, only used for debug
      - "80:80"          # HTTP redirect
      - "443:443"        # HTTPS for production

    stdin_open: true
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: always
    volumes:
      # Only used for production-server with a domain and SSL    
      - /etc/ssl/mydomain:/etc/ssl/mydomain:ro
    networks:
      - frontnet
      - backnet
    depends_on:
      - ktv_Frontend_service
      - ktv_Backend_service
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "30"

  ktv_Frontend_service:
    image: ${REGISTRY}/ktv_ecotel_frontend_img:${VERSION}
    # target: development
    stdin_open: true
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      # For development only, to synced src code to container
      # - ./ecotel_frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - frontnet
    # ports:
    #   - "3000:80"
    # depends_on:
    #   - ecotel_backend_service
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "30"
  
  
  ktv_Backend_service:
    env_file:
      - .env_backend
    image: ${REGISTRY}/ktv_ecotel_backend_img:${VERSION}
    # target: development
    stdin_open: true
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      # For development only, to synced src code to container
      # - ./Backend:/usr/src/app
      - /usr/src/app/node_modules
      - ./serviceAccountKey.json:/usr/src/app/serviceAccountKey.json:ro
    depends_on:
      - ktv_db
    # ports:
    #   - "8080:8080"
    restart: always
    networks:
      - backnet
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "30"

  ktv_db:
    image: mongo
    container_name: ktv_mongo_db
    restart: always
    env_file:
      - .env_backend
    environment:      
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - .mongodb-data:/data/db
    networks:
      - backnet 
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "30"
  
  ktv_grafana:
    image: grafana/grafana
    container_name: ktv_grafana
    ports:
      - "4000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "30"

  ktv_loki:
    image: grafana/loki:2.9.0
    container_name: ktv_loki
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./release-loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki-data:/loki
    networks:
      - monitoring
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "30"

  ktv_promtail:
    image: grafana/promtail:2.9.0
    container_name: ktv_promtail
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - promtail-state:/tmp/promtail
      - /var/log:/var/log
      - /etc/machine-id:/etc/machine-id
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./release-promtail-config.yaml:/etc/promtail/promtail.yaml
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - monitoring
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "30"

  ktv_backup:
    env_file:
      - .env_backend
    image: ${REGISTRY}/ktv_ecotel_backup_img:${VERSION}
    container_name: mongo_backup
    environment:
      - TZ=Asia/Ho_Chi_Minh
    depends_on:
      - ktv_db
    restart: unless-stopped
    networks:
      - backnet
    volumes:
      - .mongodb_backup:/app/backup
      - .mongodb_restore:/app/restore
    # This keeps the cron container running
    command: ["cron", "-f"]
networks:
  frontnet:
  backnet:
  monitoring:

volumes:
  promtail-state:
  loki-data:
  grafana-storage:
  .mongodb_backup:
  .mongodb_restore:
  


